// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SftpBackgroundExercise;

#nullable disable

namespace SftpBackgroundExercise.Migrations
{
    [DbContext(typeof(FileDBContext))]
    [Migration("20230417000235_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SftpBackgroundExercise.FileRecord", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MigratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FileName");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
